### ISSUE TITLE
OpenSubtitles captcha

### ISSUE THREAD

**Issue by Debuggernaut** [chpatrick/opensubtitles-netflix#21]
Hey, I just downloaded and really love this extension

It looks like it can't use my OpenSubtitles account, though, since they added a million captchas to the site

Is there some quick and dirty hack you could put in to have users grab the API token themselves and drop it in?  (I don't know how to build, sign, and load chrome extensions or I might be able to do it myself..)

Thanks in advance

**Comment by chpatrick** [comment]
Hi, I found that login was broken due to cross-origin issues. This should be fixed in version 1.18. Could you give it a shot?

**Comment by Debuggernaut** [comment]
Thanks!
