### ISSUE TITLE
Not an Issue, a Question

### ISSUE THREAD

**Issue by 143396** [chpatrick/opensubtitles-netflix#8]
I don't know how to contact you, so I am doing this. When I load the dfxp file it shows up as " 'name'.dfxp" in the subtitles menu. Is there any way to change that so, for example, it shows up as "English" in the subtitle menu?

**Comment by chpatrick** [comment]
That part is handled by Netflix so I don't have any control over that unfortunately. :)

**Comment by 143396** [comment]
Ok, thank you. Awesome work.
